config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :create, :show, :new]
  resource :session, only: [:create, :destroy, :new]
  resources :bands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  # write the method name for generating session token
  after_initialize :ensure_session_token

  attr_reader :password

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :logout!, :current_user
  def login!(user)
    session[:session_token] = user.reset_session_token!
  end
  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  def current_user
    # debugger
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  def logged_in?
    !!current_user
    # self.session_token ==
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end
  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end
  def new
    @band = Band.new
    render :new
  end
  def create
    @band = Band.new(clean_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:error] = 'How could you get the only input wrong?'
      render :new
    end
  end
  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end
  def update
    @band = Band.find_by(name: name)
    if @band.update_attributes(clean_params)
      redirect_to band_url(@band)
    else
      flash.now[:error] = ['how could you get the only input wrong?']
      render :edit
    end
  end
  def destroy
    @band = Band.find_by(name: name)
    @band.destroy
    render :index
  end

  private
  def clean_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user.nil?
      flash.now[:error] = ["Email is not signed up!"]
      render :new
    else
      login!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    logout!
    render :new
  end

  private
  def clean_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    render :index
  end
  def new
    @new = User.new
    render :new
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def create
    @user = User.new(clean_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def clean_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/edit.html.erb
<h1>CHANGE THIS BAND!!!!!!</h1>
<br>
<br>
<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">

    <label>BAND NAME :
      <input name="band[name]" value="<%= @band.name %>">
    </label>
    <br>
  <input type="submit" value="CHANGE THESE THINGS!">
</form>

app/views/bands/index.html.erb
<h1>ALL THE BANDSSSS</h1>
<ul>

  <% @bands.each do |band| %>
  <li> <%= band.name %> </li>
  <!-- <li>
    <form action="<%#= redirect_to edit_band_url(band) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%#= form_authenticity_token %>">
    <input type="submit" name="" value="Edit Band!!!">
  </form> </li> -->
  <% end %>
</ul>

app/views/bands/new.html.erb
<h1>CREATE THIS BAND?</h1>
<br>
<br>
<form action="<%= bands_url %> " method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if flash.now %>
    <%= flash.now[:error].to_s %>
  <% end %>
  <br>
  <br>
  <br>
  <label> Create this named band :
    <input type="text" name="band[name]" value="">
  </label>
  <br>
  <input type="submit" name="" value="CREATE BAND">
</form>

app/views/bands/show.html.erb
<h1>THE <%= @band.name.upcase %> is sickkk!!!! </h1>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header>
      <h1 class="one_true_header">MUSIC APP</h1>
      <% if logged_in? %>
        <form class="" action="<%= session_url %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="submit" value="Logout!">
        </form>
      <% else %>
        <form class="log_some" action="<%= new_session_url %>" method="get">
          <input type="submit" value="Sign In!">
        </form>
        <form class="log_some" action=" <%= new_user_url %>" method="get">
          <input type="submit" value="Sign Up!">
        </form>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>

  <% @user.each do |user| %>
    <li> <%= user.email %> </li>

  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<form action=" <%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">
  <% if flash.now[:error].nil? == false %>
    <ul>
      <%  flash.now[:error].each do |error| %>
      <li> <%= error %> </li>
      <% end %>
    </ul>
  <% end %>
  <label>Username :
    <input type="text" name="user[email]" value="">
  </label>
    <br>
  <label>Password :
    <input type="password" name="user[password]" value="">
  </label>
    <br>
    <br>
  <input type="submit" value="Create this User!!!">

</form>

app/views/users/show.html.erb
<h1> Your email is: <%= @user.email %>! </h1>